import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, ptr } = FFIType;

export const audioSymbols = {
  InitAudioDeviceW: { args: [], returns: FFIType.void },
  CloseAudioDeviceW: { args: [], returns: FFIType.void },
  IsAudioDeviceReadyW: { args: [], returns: bool },
  SetMasterVolumeW: { args: [i32], returns: FFIType.void },
  GetMasterVolumeW: { args: [], returns: i32 },
  LoadWaveW: { args: [cstring], returns: i32 },
  LoadWaveFromMemoryW: { args: [cstring, ptr, i32], returns: i32 },
  IsWaveValidW: { args: [i32], returns: bool },
  UnloadWaveW: { args: [i32], returns: FFIType.void },
  ExportWaveW: { args: [i32, cstring], returns: bool },
  ExportWaveAsCodeW: { args: [i32, cstring], returns: bool },
  WaveCopyW: { args: [i32], returns: i32 },
  WaveCropW: { args: [i32, i32, i32], returns: FFIType.void },
  WaveFormatW: { args: [i32, i32, i32, i32], returns: FFIType.void },
  LoadSoundW: { args: [cstring], returns: i32 },
  LoadSoundFromWaveW: { args: [i32], returns: i32 },
  LoadSoundAliasW: { args: [i32], returns: i32 },
  IsSoundValidW: { args: [i32], returns: bool },
  UnloadSoundW: { args: [i32], returns: FFIType.void },
  UnloadSoundAliasW: { args: [i32], returns: FFIType.void },
  PlaySoundW: { args: [i32], returns: FFIType.void },
  StopSoundW: { args: [i32], returns: FFIType.void },
  PauseSoundW: { args: [i32], returns: FFIType.void },
  ResumeSoundW: { args: [i32], returns: FFIType.void },
  IsSoundPlayingW: { args: [i32], returns: bool },
  SetSoundVolumeW: { args: [i32, i32], returns: FFIType.void },
  SetSoundPitchW: { args: [i32, i32], returns: FFIType.void },
  SetSoundPanW: { args: [i32, i32], returns: FFIType.void },
  LoadMusicStreamW: { args: [cstring], returns: i32 },
  LoadMusicStreamFromMemoryW: { args: [cstring, ptr, i32], returns: i32 },
  IsMusicValidW: { args: [i32], returns: bool },
  UnloadMusicStreamW: { args: [i32], returns: FFIType.void },
  PlayMusicStreamW: { args: [i32], returns: FFIType.void },
  IsMusicStreamPlayingW: { args: [i32], returns: bool },
  UpdateMusicStreamW: { args: [i32], returns: FFIType.void },
  StopMusicStreamW: { args: [i32], returns: FFIType.void },
  PauseMusicStreamW: { args: [i32], returns: FFIType.void },
  ResumeMusicStreamW: { args: [i32], returns: FFIType.void },
  SeekMusicStreamW: { args: [i32, i32], returns: FFIType.void },
  SetMusicVolumeW: { args: [i32, i32], returns: FFIType.void },
  SetMusicPitchW: { args: [i32, i32], returns: FFIType.void },
  SetMusicPanW: { args: [i32, i32], returns: FFIType.void },
  GetMusicTimeLengthW: { args: [i32], returns: i32 },
  GetMusicTimePlayedW: { args: [i32], returns: i32 },
  LoadAudioStreamW: { args: [i32, i32, i32], returns: i32 },
  IsAudioStreamValidW: { args: [i32], returns: bool },
  UnloadAudioStreamW: { args: [i32], returns: FFIType.void },
  IsAudioStreamProcessedW: { args: [i32], returns: bool },
  PlayAudioStreamW: { args: [i32], returns: FFIType.void },
  PauseAudioStreamW: { args: [i32], returns: FFIType.void },
  ResumeAudioStreamW: { args: [i32], returns: FFIType.void },
  IsAudioStreamPlayingW: { args: [i32], returns: bool },
  StopAudioStreamW: { args: [i32], returns: FFIType.void },
  SetAudioStreamVolumeW: { args: [i32, i32], returns: FFIType.void },
  SetAudioStreamPitchW: { args: [i32, i32], returns: FFIType.void },
  SetAudioStreamPanW: { args: [i32, i32], returns: FFIType.void },
  SetAudioStreamBufferSizeDefaultW: { args: [i32], returns: FFIType.void },
  LoadWaveSamplesW: { args: [i32], returns: ptr },
  UnloadWaveSamplesW: { args: [ptr], returns: FFIType.void },
} as const;
