import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, f32, ptr } = FFIType;

export const fontSymbols = {
  LoadFontW: { args: [cstring], returns: i32 },
  LoadFontExW: { args: [cstring, i32], returns: i32 },
  GetFontDefaultW: { args: [], returns: i32 },
  UnloadFontW: { args: [i32], returns: FFIType.void },
  IsFontValidW: { args: [i32], returns: bool },
  MeasureTextW: { args: [cstring, i32], returns: i32 },
  MeasureTextExW: { args: [ptr, i32, cstring, f32, f32], returns: FFIType.void },
  DrawTextExW: { args: [i32, cstring, f32, f32, f32, f32, i32], returns: FFIType.void },
  DrawTextProW: {
    args: [i32, cstring, f32, f32, f32, f32, f32, f32, f32, i32],
    returns: FFIType.void,
  },
  SetTextLineSpacingW: { args: [i32], returns: FFIType.void },
  LoadFontFromImageW: { args: [i32, i32, i32], returns: i32 },
  LoadFontFromMemoryW: { args: [cstring, ptr, i32, i32], returns: i32 },
  ExportFontAsCodeW: { args: [i32, cstring], returns: bool },
  DrawTextCodepointW: { args: [i32, i32, f32, f32, f32, i32], returns: FFIType.void },
  DrawTextCodepointsW: { args: [i32, ptr, i32, f32, f32, f32, f32, i32], returns: FFIType.void },
  GetGlyphIndexW: { args: [i32, i32], returns: i32 },
  GetGlyphInfoW: { args: [ptr, ptr, ptr, ptr, ptr, i32, i32], returns: FFIType.void },
  GetGlyphAtlasRecW: { args: [ptr, i32, i32], returns: FFIType.void },
  GetCodepointW: { args: [cstring, ptr], returns: i32 },
  GetCodepointNextW: { args: [cstring, ptr], returns: i32 },
  GetCodepointPreviousW: { args: [cstring, ptr], returns: i32 },
  GetCodepointCountW: { args: [cstring], returns: i32 },
  TextIsEqualW: { args: [cstring, cstring], returns: bool },
  TextLengthW: { args: [cstring], returns: i32 },
  TextToIntegerW: { args: [cstring], returns: i32 },
  TextToFloatW: { args: [cstring], returns: f32 },
  TextFindIndexW: { args: [cstring, cstring], returns: i32 },
  UnloadFontDataW: { args: [ptr, i32], returns: FFIType.void },
  UnloadUTF8W: { args: [ptr], returns: FFIType.void },
  UnloadCodepointsW: { args: [ptr], returns: FFIType.void },
  TextCopyW: { args: [ptr, cstring], returns: i32 },
  TextAppendW: { args: [ptr, cstring, ptr], returns: FFIType.void },
} as const;
