import { FFIType } from "bun:ffi";
const { i32, cstring, bool, ptr } = FFIType;

export const imageSymbols = {
  LoadImageW: { args: [cstring], returns: i32 },
  LoadImageRawW: { args: [cstring, i32, i32, i32, i32], returns: i32 },
  LoadImageAnimW: { args: [ptr, ptr, cstring], returns: FFIType.void },
  LoadImageFromMemoryW: { args: [cstring, ptr, i32], returns: i32 },
  LoadImageFromTextureW: { args: [i32, i32, i32], returns: i32 },
  LoadImageFromScreenW: { args: [], returns: i32 },
  IsImageValidW: { args: [i32], returns: bool },
  UnloadImageW: { args: [i32], returns: FFIType.void },
  ExportImageW: { args: [i32, cstring], returns: bool },
  ExportImageAsCodeW: { args: [i32, cstring], returns: bool },
  GenImageColorW: { args: [i32, i32, i32], returns: i32 },
  GenImageGradientLinearW: { args: [i32, i32, i32, i32, i32], returns: i32 },
  GenImageGradientRadialW: { args: [i32, i32, i32, i32, i32], returns: i32 },
  GenImageGradientSquareW: { args: [i32, i32, i32, i32, i32], returns: i32 },
  GenImageCheckedW: { args: [i32, i32, i32, i32, i32, i32], returns: i32 },
  GenImageWhiteNoiseW: { args: [i32, i32, i32], returns: i32 },
  GenImagePerlinNoiseW: { args: [i32, i32, i32, i32, i32], returns: i32 },
  GenImageCellularW: { args: [i32, i32, i32], returns: i32 },
  GenImageTextW: { args: [i32, i32, cstring], returns: i32 },
  ImageCopyW: { args: [i32], returns: i32 },
  ImageFromImageW: { args: [i32, i32, i32, i32, i32], returns: i32 },
  ImageFromChannelW: { args: [i32, i32], returns: i32 },
  ImageTextW: { args: [cstring, i32, i32], returns: i32 },
  ImageTextExW: { args: [i32, cstring, i32, i32, i32], returns: i32 },
  ImageFormatW: { args: [i32, i32], returns: FFIType.void },
  ImageCropW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageAlphaCropW: { args: [i32, i32], returns: FFIType.void },
  ImageAlphaClearW: { args: [i32, i32, i32], returns: FFIType.void },
  ImageAlphaMaskW: { args: [i32, i32], returns: FFIType.void },
  ImageAlphaPremultiplyW: { args: [i32], returns: FFIType.void },
  ImageBlurGaussianW: { args: [i32, i32], returns: FFIType.void },
  ImageResizeW: { args: [i32, i32, i32], returns: FFIType.void },
  ImageResizeNNW: { args: [i32, i32, i32], returns: FFIType.void },
  ImageResizeCanvasW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageMipmapsW: { args: [i32], returns: FFIType.void },
  ImageDitherW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageFlipVerticalW: { args: [i32], returns: FFIType.void },
  ImageFlipHorizontalW: { args: [i32], returns: FFIType.void },
  ImageRotateW: { args: [i32, i32], returns: FFIType.void },
  ImageRotateCWW: { args: [i32], returns: FFIType.void },
  ImageRotateCCWW: { args: [i32], returns: FFIType.void },
  ImageColorTintW: { args: [i32, i32], returns: FFIType.void },
  ImageColorInvertW: { args: [i32], returns: FFIType.void },
  ImageColorGrayscaleW: { args: [i32], returns: FFIType.void },
  ImageColorContrastW: { args: [i32, i32], returns: FFIType.void },
  ImageColorBrightnessW: { args: [i32, i32], returns: FFIType.void },
  ImageColorReplaceW: { args: [i32, i32, i32], returns: FFIType.void },
  GetImageAlphaBorderW: { args: [ptr, i32, i32], returns: FFIType.void },
  GetImageColorW: { args: [i32, i32, i32], returns: i32 },
  ImageClearBackgroundW: { args: [i32, i32], returns: FFIType.void },
  ImageDrawPixelW: { args: [i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawPixelVW: { args: [i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawLineW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawLineVW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawLineExW: { args: [i32, i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawCircleW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawCircleVW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawCircleLinesW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawCircleLinesVW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawRectangleW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawRectangleVW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawRectangleRecW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawRectangleLinesW: { args: [i32, i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawTriangleW: { args: [i32, i32, i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawTriangleExW: {
    args: [i32, i32, i32, i32, i32, i32, i32, i32, i32, i32],
    returns: FFIType.void,
  },
  ImageDrawTriangleLinesW: {
    args: [i32, i32, i32, i32, i32, i32, i32, i32],
    returns: FFIType.void,
  },
  ImageDrawTriangleFanW: { args: [i32, ptr, i32, i32], returns: FFIType.void },
  ImageDrawTriangleStripW: { args: [i32, ptr, i32, i32], returns: FFIType.void },
  ImageDrawW: {
    args: [i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32],
    returns: FFIType.void,
  },
  ImageDrawTextW: { args: [i32, cstring, i32, i32, i32, i32], returns: FFIType.void },
  ImageDrawTextExW: { args: [i32, i32, cstring, i32, i32, i32, i32, i32], returns: FFIType.void },
  ImageToPOTW: { args: [i32, i32], returns: FFIType.void },
  ImageKernelConvolutionW: { args: [i32, ptr, i32], returns: FFIType.void },
  UnloadImageColorsW: { args: [ptr], returns: FFIType.void },
  UnloadImagePaletteW: { args: [ptr], returns: FFIType.void },
  LoadImageAnimFromMemoryW: { args: [cstring, ptr, i32, ptr], returns: i32 },
} as const;
