import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, f32, ptr, } = FFIType;

export const inputSymbols = {
  IsKeyPressedW: { args: [i32], returns: bool },
  IsKeyPressedRepeatW: { args: [i32], returns: bool },
  IsKeyDownW: { args: [i32], returns: bool },
  IsKeyReleasedW: { args: [i32], returns: bool },
  IsKeyUpW: { args: [i32], returns: bool },
  GetKeyPressedW: { args: [], returns: i32 },
  GetCharPressedW: { args: [], returns: i32 },
  SetExitKeyW: { args: [i32], returns: FFIType.void },
  IsGamepadAvailableW: { args: [i32], returns: bool },
  GetGamepadNameW: { args: [i32], returns: ptr },
  IsGamepadButtonPressedW: { args: [i32, i32], returns: bool },
  IsGamepadButtonDownW: { args: [i32, i32], returns: bool },
  IsGamepadButtonReleasedW: { args: [i32, i32], returns: bool },
  IsGamepadButtonUpW: { args: [i32, i32], returns: bool },
  GetGamepadButtonPressedW: { args: [], returns: i32 },
  GetGamepadAxisCountW: { args: [i32], returns: i32 },
  GetGamepadAxisMovementW: { args: [i32, i32], returns: f32 },
  SetGamepadMappingsW: { args: [cstring], returns: i32 },
  SetGamepadVibrationW: { args: [i32, f32, f32, f32], returns: FFIType.void },
  IsMouseButtonPressedW: { args: [i32], returns: bool },
  IsMouseButtonDownW: { args: [i32], returns: bool },
  IsMouseButtonReleasedW: { args: [i32], returns: bool },
  IsMouseButtonUpW: { args: [i32], returns: bool },
  GetMouseXW: { args: [], returns: i32 },
  GetMouseYW: { args: [], returns: i32 },
  GetMousePositionW: { args: [ptr], returns: FFIType.void },
  GetMouseDeltaW: { args: [ptr], returns: FFIType.void },
  SetMousePositionW: { args: [i32, i32], returns: FFIType.void },
  SetMouseOffsetW: { args: [i32, i32], returns: FFIType.void },
  SetMouseScaleW: { args: [f32, f32], returns: FFIType.void },
  GetMouseWheelMoveW: { args: [], returns: f32 },
  GetMouseWheelMoveVW: { args: [ptr], returns: FFIType.void },
  SetMouseCursorW: { args: [i32], returns: FFIType.void },
  GetTouchXW: { args: [], returns: i32 },
  GetTouchYW: { args: [], returns: i32 },
  GetTouchPositionW: { args: [ptr, i32], returns: FFIType.void },
  GetTouchPointIdW: { args: [i32], returns: i32 },
  GetTouchPointCountW: { args: [], returns: i32 },
  SetGesturesEnabledW: { args: [i32], returns: FFIType.void },
  IsGestureDetectedW: { args: [i32], returns: bool },
  GetGestureDetectedW: { args: [], returns: i32 },
  GetGestureHoldDurationW: { args: [], returns: f32 },
  GetGestureDragVectorW: { args: [ptr], returns: FFIType.void },
  GetGestureDragAngleW: { args: [], returns: f32 },
  GetGesturePinchVectorW: { args: [ptr], returns: FFIType.void },
  GetGesturePinchAngleW: { args: [], returns: f32 },
} as const;
