import { FFIType } from "bun:ffi";
const { i32, cstring, bool, ptr } = FFIType;

export const modelSymbols = {
  LoadModelW: { args: [cstring], returns: i32 },
  UnloadModelW: { args: [i32], returns: FFIType.void },
  IsModelValidW: { args: [i32], returns: bool },
  GetModelBoundingBoxW: { args: [ptr, ptr, i32], returns: FFIType.void },
  LoadModelFromMeshW: { args: [i32], returns: i32 },
  UnloadMeshW: { args: [i32], returns: FFIType.void },
  UploadMeshW: { args: [i32, bool], returns: FFIType.void },
  GetMeshBoundingBoxW: { args: [ptr, ptr, i32], returns: FFIType.void },
  GenMeshTangentsW: { args: [i32], returns: FFIType.void },
  ExportMeshW: { args: [i32, cstring], returns: bool },
  ExportMeshAsCodeW: { args: [i32, cstring], returns: bool },
  GenMeshPolyW: { args: [i32, i32], returns: i32 },
  GenMeshPlaneW: { args: [i32, i32, i32, i32], returns: i32 },
  GenMeshCubeW: { args: [i32, i32, i32], returns: i32 },
  GenMeshSphereW: { args: [i32, i32, i32], returns: i32 },
  GenMeshHemiSphereW: { args: [i32, i32, i32], returns: i32 },
  GenMeshCylinderW: { args: [i32, i32, i32], returns: i32 },
  GenMeshConeW: { args: [i32, i32, i32], returns: i32 },
  GenMeshTorusW: { args: [i32, i32, i32, i32], returns: i32 },
  GenMeshKnotW: { args: [i32, i32, i32, i32], returns: i32 },
  GenMeshHeightmapW: { args: [i32, i32, i32, i32], returns: i32 },
  GenMeshCubicmapW: { args: [i32, i32, i32, i32], returns: i32 },
  UpdateMeshBufferW: { args: [i32, i32, ptr, i32, i32], returns: FFIType.void },
  LoadMaterialDefaultW: { args: [], returns: i32 },
  IsMaterialValidW: { args: [i32], returns: bool },
  UnloadMaterialW: { args: [i32], returns: FFIType.void },
  SetMaterialTextureW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  SetModelMeshMaterialW: { args: [i32, i32, i32], returns: FFIType.void },
  LoadModelAnimationsW: { args: [ptr, ptr, cstring], returns: FFIType.void },
  UpdateModelAnimationW: { args: [i32, i32, i32], returns: FFIType.void },
  UpdateModelAnimationExW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  UnloadModelAnimationsW: { args: [i32, i32], returns: FFIType.void },
  IsModelAnimationValidW: { args: [i32, i32], returns: bool },
} as const;
