import { FFIType } from 'bun:ffi';
const { i32, ptr } = FFIType;

export const shapesSymbols = {
  DrawRectangleW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  DrawTextW: { args: [FFIType.cstring, i32, i32, i32, i32], returns: FFIType.void },
  DrawPixelW: { args: [i32, i32, i32], returns: FFIType.void },
  DrawLineW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  DrawLineExW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawLineStripW: { args: [ptr, i32, i32], returns: FFIType.void },
  DrawLineBezierW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawCircleW: { args: [i32, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawCircleSectorW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawCircleSectorLinesW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawCircleGradientW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawCircleLinesW: { args: [i32, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawEllipseW: { args: [i32, i32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawEllipseLinesW: { args: [i32, i32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawRingW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawRingLinesW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawRectangleProW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawRectangleGradientVW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  DrawRectangleGradientHW: { args: [i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  DrawRectangleGradientExW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32, i32, i32],
    returns: FFIType.void,
  },
  DrawRectangleLinesW: { args: [i32, i32, i32, i32, i32], returns: FFIType.void },
  DrawRectangleLinesExW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawRectangleRoundedW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawRectangleRoundedLinesW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, i32], returns: FFIType.void },
  DrawRectangleRoundedLinesExW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32, FFIType.f32, i32],
    returns: FFIType.void,
  },
  DrawTriangleW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawTriangleLinesW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawTriangleFanW: { args: [ptr, i32, i32], returns: FFIType.void },
  DrawTriangleStripW: { args: [ptr, i32, i32], returns: FFIType.void },
  DrawPolyW: { args: [FFIType.f32, FFIType.f32, i32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawPolyLinesW: { args: [FFIType.f32, FFIType.f32, i32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawPolyLinesExW: { args: [FFIType.f32, FFIType.f32, i32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineLinearW: { args: [ptr, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineBasisW: { args: [ptr, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineCatmullRomW: { args: [ptr, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineBezierQuadraticW: { args: [ptr, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineBezierCubicW: { args: [ptr, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineSegmentLinearW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawSplineSegmentBasisW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32],
    returns: FFIType.void,
  },
  DrawSplineSegmentCatmullRomW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32],
    returns: FFIType.void,
  },
  DrawSplineSegmentBezierQuadraticW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32],
    returns: FFIType.void,
  },
  DrawSplineSegmentBezierCubicW: {
    args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32],
    returns: FFIType.void,
  },
  GetSplinePointLinearW: { args: [ptr, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32], returns: FFIType.void },
  GetSplinePointBasisW: {
    args: [ptr, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32],
    returns: FFIType.void,
  },
  GetSplinePointCatmullRomW: {
    args: [ptr, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32],
    returns: FFIType.void,
  },
  GetSplinePointBezierQuadW: {
    args: [ptr, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32],
    returns: FFIType.void,
  },
  GetSplinePointBezierCubicW: {
    args: [ptr, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32],
    returns: FFIType.void,
  },
  DrawPixelVW: { args: [FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawLineVW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawCircleVW: { args: [i32, i32, FFIType.f32, i32], returns: FFIType.void },
  DrawCircleLinesVW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawRectangleVW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  DrawRectangleRecW: { args: [FFIType.f32, FFIType.f32, FFIType.f32, FFIType.f32, i32], returns: FFIType.void },
  SetShapesTextureW: { args: [i32, i32, i32, i32, i32, i32, i32], returns: FFIType.void },
  GetShapesTextureW: { args: [ptr, ptr, ptr], returns: FFIType.void },
  GetShapesTextureRectangleW: { args: [ptr], returns: FFIType.void },
  DrawFPSW: { args: [i32, i32], returns: FFIType.void },
} as const;
