import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, f32, ptr } = FFIType;

export const windowSymbols = {
  InitWindowW: { args: [i32, i32, cstring], returns: FFIType.void },
  CloseWindowW: { args: [], returns: FFIType.void },
  WindowShouldCloseW: { args: [], returns: bool },
  BeginDrawingW: { args: [], returns: FFIType.void },
  EndDrawingW: { args: [], returns: FFIType.void },
  ClearBackgroundW: { args: [i32], returns: FFIType.void },
  SetTargetFPSW: { args: [i32], returns: FFIType.void },
  GetFrameTimeW: { args: [], returns: f32 },

  IsWindowReadyW: { args: [], returns: bool },
  IsWindowFullscreenW: { args: [], returns: bool },
  IsWindowHiddenW: { args: [], returns: bool },
  IsWindowMinimizedW: { args: [], returns: bool },
  IsWindowMaximizedW: { args: [], returns: bool },
  IsWindowFocusedW: { args: [], returns: bool },
  IsWindowResizedW: { args: [], returns: bool },
  IsWindowStateW: { args: [i32], returns: bool },
  SetWindowStateW: { args: [i32], returns: FFIType.void },
  ClearWindowStateW: { args: [i32], returns: FFIType.void },
  ToggleFullscreenW: { args: [], returns: FFIType.void },
  ToggleBorderlessWindowedW: { args: [], returns: FFIType.void },
  MaximizeWindowW: { args: [], returns: FFIType.void },
  MinimizeWindowW: { args: [], returns: FFIType.void },
  RestoreWindowW: { args: [], returns: FFIType.void },
  SetWindowTitleW: { args: [cstring], returns: FFIType.void },
  SetWindowPositionW: { args: [i32, i32], returns: FFIType.void },
  SetWindowMonitorW: { args: [i32], returns: FFIType.void },
  SetWindowMinSizeW: { args: [i32, i32], returns: FFIType.void },
  SetWindowMaxSizeW: { args: [i32, i32], returns: FFIType.void },
  SetWindowSizeW: { args: [i32, i32], returns: FFIType.void },
  SetWindowOpacityW: { args: [f32], returns: FFIType.void },
  SetWindowFocusedW: { args: [], returns: FFIType.void },
  GetScreenWidthW: { args: [], returns: i32 },
  GetScreenHeightW: { args: [], returns: i32 },
  GetRenderWidthW: { args: [], returns: i32 },
  GetRenderHeightW: { args: [], returns: i32 },
  GetMonitorCountW: { args: [], returns: i32 },
  GetCurrentMonitorW: { args: [], returns: i32 },
  GetMonitorPositionW: { args: [ptr, i32], returns: FFIType.void },
  GetMonitorWidthW: { args: [i32], returns: i32 },
  GetMonitorHeightW: { args: [i32], returns: i32 },
  GetMonitorPhysicalWidthW: { args: [i32], returns: i32 },
  GetMonitorPhysicalHeightW: { args: [i32], returns: i32 },
  GetMonitorRefreshRateW: { args: [i32], returns: i32 },
  GetWindowPositionW: { args: [ptr], returns: FFIType.void },
  GetWindowScaleDPIW: { args: [ptr], returns: FFIType.void },
  GetMonitorNameW: { args: [i32], returns: ptr },
  SetClipboardTextW: { args: [cstring], returns: FFIType.void },
  GetClipboardTextW: { args: [], returns: ptr },
  EnableEventWaitingW: { args: [], returns: FFIType.void },
  DisableEventWaitingW: { args: [], returns: FFIType.void },
  ShowCursorW: { args: [], returns: FFIType.void },
  HideCursorW: { args: [], returns: FFIType.void },
  IsCursorHiddenW: { args: [], returns: bool },
  EnableCursorW: { args: [], returns: FFIType.void },
  DisableCursorW: { args: [], returns: FFIType.void },
  IsCursorOnScreenW: { args: [], returns: bool },
  BeginTextureModeW: { args: [i32, i32, i32], returns: FFIType.void },
  EndTextureModeW: { args: [], returns: FFIType.void },
  BeginBlendModeW: { args: [i32], returns: FFIType.void },
  EndBlendModeW: { args: [], returns: FFIType.void },
  BeginScissorModeW: { args: [i32, i32, i32, i32], returns: FFIType.void },
  EndScissorModeW: { args: [], returns: FFIType.void },
  GetTimeW: { args: [], returns: FFIType.f64 },
  GetFPSW: { args: [], returns: i32 },
  SwapScreenBufferW: { args: [], returns: FFIType.void },
  PollInputEventsW: { args: [], returns: FFIType.void },
  WaitTimeW: { args: [FFIType.f64], returns: FFIType.void },
  SetRandomSeedW: { args: [i32], returns: FFIType.void },
  GetRandomValueW: { args: [i32, i32], returns: i32 },
  TakeScreenshotW: { args: [cstring], returns: FFIType.void },
  SetConfigFlagsW: { args: [i32], returns: FFIType.void },
  OpenURLW: { args: [cstring], returns: FFIType.void },
  TraceLogW: { args: [i32, cstring], returns: FFIType.void },
  SetTraceLogLevelW: { args: [i32], returns: FFIType.void },
  SetWindowIconW: { args: [i32], returns: FFIType.void },
  GetClipboardImageW: { args: [], returns: i32 },
  SetWindowIconsW: { args: [ptr, i32], returns: FFIType.void },
} as const;
