import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, f32, ptr } = FFIType;

export const inputDirectSymbols = {
  IsKeyPressed: { args: [i32], returns: bool },
  IsKeyPressedRepeat: { args: [i32], returns: bool },
  IsKeyDown: { args: [i32], returns: bool },
  IsKeyReleased: { args: [i32], returns: bool },
  IsKeyUp: { args: [i32], returns: bool },
  GetKeyPressed: { args: [], returns: i32 },
  GetCharPressed: { args: [], returns: i32 },
  SetExitKey: { args: [i32], returns: FFIType.void },
  IsGamepadAvailable: { args: [i32], returns: bool },
  GetGamepadName: { args: [i32], returns: ptr },
  IsGamepadButtonPressed: { args: [i32, i32], returns: bool },
  IsGamepadButtonDown: { args: [i32, i32], returns: bool },
  IsGamepadButtonReleased: { args: [i32, i32], returns: bool },
  IsGamepadButtonUp: { args: [i32, i32], returns: bool },
  GetGamepadButtonPressed: { args: [], returns: i32 },
  GetGamepadAxisCount: { args: [i32], returns: i32 },
  GetGamepadAxisMovement: { args: [i32, i32], returns: f32 },
  SetGamepadMappings: { args: [cstring], returns: i32 },
  SetGamepadVibration: { args: [i32, f32, f32, f32], returns: FFIType.void },
  IsMouseButtonPressed: { args: [i32], returns: bool },
  IsMouseButtonDown: { args: [i32], returns: bool },
  IsMouseButtonReleased: { args: [i32], returns: bool },
  IsMouseButtonUp: { args: [i32], returns: bool },
  GetMouseX: { args: [], returns: i32 },
  GetMouseY: { args: [], returns: i32 },
  SetMousePosition: { args: [i32, i32], returns: FFIType.void },
  SetMouseOffset: { args: [i32, i32], returns: FFIType.void },
  SetMouseScale: { args: [f32, f32], returns: FFIType.void },
  GetMouseWheelMove: { args: [], returns: f32 },
  SetMouseCursor: { args: [i32], returns: FFIType.void },
  GetTouchX: { args: [], returns: i32 },
  GetTouchY: { args: [], returns: i32 },
  GetTouchPointId: { args: [i32], returns: i32 },
  GetTouchPointCount: { args: [], returns: i32 },
  SetGesturesEnabled: { args: [i32], returns: FFIType.void },
  IsGestureDetected: { args: [i32], returns: bool },
  GetGestureDetected: { args: [], returns: i32 },
  GetGestureHoldDuration: { args: [], returns: f32 },
  GetGestureDragAngle: { args: [], returns: f32 },
  GetGesturePinchAngle: { args: [], returns: f32 },
} as const;

export const inputWrapperSymbols = {
  GetMousePositionW: { args: [ptr], returns: FFIType.void },
  GetMouseDeltaW: { args: [ptr], returns: FFIType.void },
  GetMouseWheelMoveVW: { args: [ptr], returns: FFIType.void },
  GetTouchPositionW: { args: [ptr, i32], returns: FFIType.void },
  GetGestureDragVectorW: { args: [ptr], returns: FFIType.void },
  GetGesturePinchVectorW: { args: [ptr], returns: FFIType.void },
} as const;
