import { FFIType } from 'bun:ffi';
const { i32, f32, bool } = FFIType;

export const audioDirectSymbols = {
  InitAudioDevice: { args: [], returns: FFIType.void },
  CloseAudioDevice: { args: [], returns: FFIType.void },
  IsAudioDeviceReady: { args: [], returns: bool },
  SetMasterVolume: { args: [f32], returns: FFIType.void },
  GetMasterVolume: { args: [], returns: f32 },
  SetAudioStreamBufferSizeDefault: { args: [i32], returns: FFIType.void },
} as const;

export const audioWrapperSymbols = {
  LoadWaveW: { args: [FFIType.cstring], returns: i32 },
  LoadWaveFromMemoryW: { args: [FFIType.cstring, FFIType.ptr, i32], returns: i32 },
  IsWaveValidW: { args: [i32], returns: FFIType.bool },
  UnloadWaveW: { args: [i32], returns: FFIType.void },
  ExportWaveW: { args: [i32, FFIType.cstring], returns: FFIType.bool },
  ExportWaveAsCodeW: { args: [i32, FFIType.cstring], returns: FFIType.bool },
  WaveCopyW: { args: [i32], returns: i32 },
  WaveCropW: { args: [i32, i32, i32], returns: FFIType.void },
  WaveFormatW: { args: [i32, i32, i32, i32], returns: FFIType.void },
  LoadSoundW: { args: [FFIType.cstring], returns: i32 },
  LoadSoundFromWaveW: { args: [i32], returns: i32 },
  LoadSoundAliasW: { args: [i32], returns: i32 },
  IsSoundValidW: { args: [i32], returns: FFIType.bool },
  UnloadSoundW: { args: [i32], returns: FFIType.void },
  UnloadSoundAliasW: { args: [i32], returns: FFIType.void },
  PlaySoundW: { args: [i32], returns: FFIType.void },
  StopSoundW: { args: [i32], returns: FFIType.void },
  PauseSoundW: { args: [i32], returns: FFIType.void },
  ResumeSoundW: { args: [i32], returns: FFIType.void },
  IsSoundPlayingW: { args: [i32], returns: FFIType.bool },
  SetSoundVolumeW: { args: [i32, f32], returns: FFIType.void },
  SetSoundPitchW: { args: [i32, f32], returns: FFIType.void },
  SetSoundPanW: { args: [i32, f32], returns: FFIType.void },
  LoadMusicStreamW: { args: [FFIType.cstring], returns: i32 },
  LoadMusicStreamFromMemoryW: { args: [FFIType.cstring, FFIType.ptr, i32], returns: i32 },
  IsMusicValidW: { args: [i32], returns: FFIType.bool },
  UnloadMusicStreamW: { args: [i32], returns: FFIType.void },
  PlayMusicStreamW: { args: [i32], returns: FFIType.void },
  IsMusicStreamPlayingW: { args: [i32], returns: FFIType.bool },
  UpdateMusicStreamW: { args: [i32], returns: FFIType.void },
  StopMusicStreamW: { args: [i32], returns: FFIType.void },
  PauseMusicStreamW: { args: [i32], returns: FFIType.void },
  ResumeMusicStreamW: { args: [i32], returns: FFIType.void },
  SeekMusicStreamW: { args: [i32, f32], returns: FFIType.void },
  SetMusicVolumeW: { args: [i32, f32], returns: FFIType.void },
  SetMusicPitchW: { args: [i32, f32], returns: FFIType.void },
  SetMusicPanW: { args: [i32, f32], returns: FFIType.void },
  GetMusicTimeLengthW: { args: [i32], returns: f32 },
  GetMusicTimePlayedW: { args: [i32], returns: f32 },
  LoadAudioStreamW: { args: [i32, i32, i32], returns: i32 },
  IsAudioStreamValidW: { args: [i32], returns: FFIType.bool },
  UnloadAudioStreamW: { args: [i32], returns: FFIType.void },
  IsAudioStreamProcessedW: { args: [i32], returns: FFIType.bool },
  PlayAudioStreamW: { args: [i32], returns: FFIType.void },
  PauseAudioStreamW: { args: [i32], returns: FFIType.void },
  ResumeAudioStreamW: { args: [i32], returns: FFIType.void },
  IsAudioStreamPlayingW: { args: [i32], returns: FFIType.bool },
  StopAudioStreamW: { args: [i32], returns: FFIType.void },
  SetAudioStreamVolumeW: { args: [i32, f32], returns: FFIType.void },
  SetAudioStreamPitchW: { args: [i32, f32], returns: FFIType.void },
  SetAudioStreamPanW: { args: [i32, f32], returns: FFIType.void },
  LoadWaveSamplesW: { args: [i32], returns: FFIType.ptr },
  UnloadWaveSamplesW: { args: [FFIType.ptr], returns: FFIType.void },
  UpdateSoundW: { args: [i32, FFIType.ptr, i32], returns: FFIType.void },
  UpdateAudioStreamW: { args: [i32, FFIType.ptr, i32], returns: FFIType.void },
  SetAudioStreamCallbackW: { args: [i32, FFIType.ptr], returns: FFIType.void },
} as const;
