import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "fs";


const RAYLIB_H = [process.env.RAYLIB_H, "/usr/include/raylib.h", "/usr/local/include/raylib.h"].find(
  (path): path is string => !!path && existsSync(path),
);
const SYMBOLS_TS = "src/symbols.ts";
const SYMBOLS_DIR = "src/modules";
const EXAMPLES_DIR = "examples";
const TESTS_DIR = "tests";
const OUTPUT = "PROGRESS.md";

// ─── Registry: functions intentionally skipped ─────────────────────────────
// VR (requires Oculus Rift), filesystem I/O (Bun/Node has fs.*),
// automation events (testing-only), audio processors (niche callback FFI).
const SKIP_FUNCTIONS = new Set([
  // VR Stereo Mode
  "BeginVrStereoMode", "EndVrStereoMode", "LoadVrStereoConfig", "UnloadVrStereoConfig",
  // Automation Events
  "LoadAutomationEventList", "UnloadAutomationEventList", "ExportAutomationEventList",
  "SetAutomationEventList", "SetAutomationEventBaseFrame",
  "StartAutomationEventRecording", "StopAutomationEventRecording", "PlayAutomationEvent",
  // File Callbacks
  "SetTraceLogCallback",
  "SetLoadFileDataCallback", "SetSaveFileDataCallback",
  "SetLoadFileTextCallback", "SetSaveFileTextCallback",
  // File Drag-Drop
  "IsFileDropped", "LoadDroppedFiles", "UnloadDroppedFiles",
  // Audio Processors
  "AttachAudioStreamProcessor", "DetachAudioStreamProcessor",
  "AttachAudioMixedProcessor", "DetachAudioMixedProcessor",
  // Filesystem Utils
  "UnloadFileData", "SaveFileData", "ExportDataAsCode",
  "UnloadFileText", "SaveFileText",
  "FileRename", "FileRemove", "FileCopy", "FileMove",
  "FileTextReplace", "FileTextFindIndex",
  "FileExists", "DirectoryExists", "IsFileExtension",
  "GetFileLength", "GetFileModTime",
  "MakeDirectory", "ChangeDirectory", "IsPathFile", "IsFileNameValid",
  "LoadDirectoryFiles", "LoadDirectoryFilesEx", "UnloadDirectoryFiles",
  "GetDirectoryFileCount", "GetDirectoryFileCountEx",
  "ComputeCRC32", "UnloadRandomSequence", "MemFree"
]);

if (!RAYLIB_H) {
  throw new Error("Unable to locate raylib.h. Set RAYLIB_H to your raylib 6.0 header path.");
}

function collectSymbolFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = `${dir}/${entry}`;
    if (statSync(full).isDirectory()) {
      results.push(...collectSymbolFiles(full));
    } else if (entry === "symbols.ts") {
      results.push(readFileSync(full, "utf-8"));
    }
  }
  return results;
}

const h = readFileSync(RAYLIB_H, "utf-8");
const symbolSources = [
  readFileSync(SYMBOLS_TS, "utf-8"),
  ...collectSymbolFiles(SYMBOLS_DIR),
];

const implementedRaw = new Set(
  symbolSources.flatMap((source) => [...source.matchAll(/(\w+):\s*\{/g)].map((m) => m[1]!)),
);
const implemented = new Set(
  [...implementedRaw].map((s) => s.replace(/W$/, "")),
);

const exampleSources = existsSync(EXAMPLES_DIR)
  ? readdirSync(EXAMPLES_DIR)
      .filter((name) => name.endsWith(".ts") && name !== "index.ts")
      .map((name) => readFileSync(`${EXAMPLES_DIR}/${name}`, "utf-8"))
  : [];

const testSources = existsSync(TESTS_DIR)
  ? readdirSync(TESTS_DIR)
      .filter((name) => name.endsWith(".test.ts"))
      .map((name) => readFileSync(`${TESTS_DIR}/${name}`, "utf-8"))
  : [];

const exampleFuncs = new Set(
  exampleSources.flatMap((src) => [...src.matchAll(/Raylib\.(\w+)\(/g)].map((m) => m[1]!)),
);

const testFuncs = new Set(
  testSources.flatMap((src) => [...src.matchAll(/Raylib\.(\w+)\(/g)].map((m) => m[1]!)),
);

function camelFromC(cname: string): string {
  return cname[0]!.toLowerCase() + cname.slice(1);
}

interface Section {
  title: string;
  functions: string[];
}

const sections: Section[] = [];
let currentSection: Section | null = null;

const lines = h.split("\n");
const funcRe = /^RLAPI\s+\w[\w\s*]+\s+(\w+)\s*\(/;
const separatorRe = /^\/\/-{20,}/;

for (let i = 0; i < lines.length; i++) {
  const trimmed = lines[i]!.trim();

  if (separatorRe.test(trimmed)) {
    if (i + 1 < lines.length) {
      const next = lines[i + 1]!.trim();
      const titleMatch = /^\/\/\s+(.+)$/.exec(next);
      if (titleMatch) {
        const title = titleMatch[1]!.trim();
        if (
          !title.match(/^[-=]/) &&
          !title.startsWith("NOTE") &&
          !title.startsWith("WARNING")
        ) {
          currentSection = { title, functions: [] };
          sections.push(currentSection);
          continue;
        }
      }
    }
  }

  const funcMatch = funcRe.exec(trimmed);
  if (funcMatch && currentSection) {
    currentSection.functions.push(funcMatch[1]!);
  }
}

let md = `# rraylib Progress Tracker\n\n`;
md += `> Auto-generated by \`bun run progress\`\n\n`;

let totalDone = 0;
let totalSkipped = 0;
let totalFuncs = 0;

interface FnInfo {
  name: string;
  hasExample: boolean;
  hasTest: boolean;
}

interface SectionResult {
  title: string;
  done: FnInfo[];
  skipped: FnInfo[];
  missing: FnInfo[];
}

const results: SectionResult[] = [];

for (const sec of sections) {
  if (sec.functions.length === 0) continue;

  const done: FnInfo[] = [];
  const skipped: FnInfo[] = [];
  const missing: FnInfo[] = [];

  for (const fn of sec.functions) {
    const camel = camelFromC(fn);
    const info: FnInfo = {
      name: fn,
      hasExample: exampleFuncs.has(camel),
      hasTest: testFuncs.has(camel),
    };
    if (implemented.has(fn)) {
      done.push(info);
    } else if (SKIP_FUNCTIONS.has(fn)) {
      skipped.push(info);
    } else {
      missing.push(info);
    }
  }

  totalDone += done.length;
  totalSkipped += skipped.length;
  totalFuncs += done.length + skipped.length + missing.length;

  results.push({ title: sec.title, done, skipped, missing });
}

// Targetable functions = total - skipped
const targetable = totalFuncs - totalSkipped;
const pct = targetable > 0 ? ((totalDone / targetable) * 100).toFixed(1) : "0";

const allFuncs = results.flatMap((r) => [...r.done, ...r.missing]);
const totalWithExample = allFuncs.filter((f) => f.hasExample).length;
const totalWithTest = allFuncs.filter((f) => f.hasTest).length;

md += `## Overall: ${totalDone}/${targetable} (${pct}%)\n\n`;
md += `| Implemented | Skipped | Examples | Tests |\n`;
md += `|-------------|---------|----------|-------|\n`;
md += `| ${totalDone}/${targetable} | ${totalSkipped} | ${totalWithExample}/${targetable} | ${totalWithTest}/${targetable} |\n\n`;

const barLen = 30;
const filled = targetable > 0 ? Math.round((totalDone / targetable) * barLen) : 0;
md += `[${"█".repeat(filled)}${"░".repeat(barLen - filled)}]\n\n`;

for (const r of results) {
  const total = r.done.length + r.skipped.length + r.missing.length;
  const secTargetable = total - r.skipped.length;
  const secPct = secTargetable > 0 ? ((r.done.length / secTargetable) * 100).toFixed(0) : "100";
  const secExample = r.done.filter((f) => f.hasExample).length + r.missing.filter((f) => f.hasExample).length;
  const secTest = r.done.filter((f) => f.hasTest).length + r.missing.filter((f) => f.hasTest).length;
  const icon = r.missing.length === 0 && r.skipped.length === 0 ? "✅"
    : r.done.length === 0 ? "⬜"
    : r.missing.length === 0 ? "✅" : "🔶";

  const skippedTag = r.skipped.length > 0 ? ` 🚫${r.skipped.length}` : "";
  md += `### ${icon} ${r.title} (${r.done.length}/${secTargetable} — ${secPct}% | 📝${secExample} 🧪${secTest}${skippedTag})\n\n`;

  if (r.missing.length > 0) {
    md += `<details><summary><b>Missing (${r.missing.length})</b></summary>\n\n`;
    for (const fn of r.missing) {
      const ex = fn.hasExample ? "📝" : "";
      const ts = fn.hasTest ? "🧪" : "";
      md += `- [ ] \`${fn.name}\` ${ex}${ts}\n`;
    }
    md += `\n</details>\n\n`;
  }

  if (r.skipped.length > 0) {
    md += `<details><summary>🚫 Skipped (${r.skipped.length})</summary>\n\n`;
    for (const fn of r.skipped) {
      md += `- ~\`${fn.name}\`~\n`;
    }
    md += `\n</details>\n\n`;
  }

  if (r.done.length > 0) {
    md += `<details><summary>Done (${r.done.length})</summary>\n\n`;
    for (const fn of r.done) {
      const ex = fn.hasExample ? "📝" : "";
      const ts = fn.hasTest ? "🧪" : "";
      md += `- [x] \`${fn.name}\` ${ex}${ts}\n`;
    }
    md += `\n</details>\n\n`;
  }
}

writeFileSync(OUTPUT, md);
console.log(`PROGRESS.md generated: ${totalDone}/${targetable} (${pct}%) [${totalSkipped} skipped]`);
