import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";


const RAYLIB_H = [process.env.RAYLIB_H, "/usr/include/raylib.h", "/usr/local/include/raylib.h"].find(
  (path): path is string => !!path && existsSync(path),
);
const SYMBOLS_TS = "src/symbols.ts";
const SYMBOLS_DIR = "src/symbols";
const EXAMPLES_DIR = "examples";
const TESTS_DIR = "tests";
const OUTPUT = "PROGRESS.md";

if (!RAYLIB_H) {
  throw new Error("Unable to locate raylib.h. Set RAYLIB_H to your raylib 6.0 header path.");
}

const h = readFileSync(RAYLIB_H, "utf-8");
const symbolSources = [
  readFileSync(SYMBOLS_TS, "utf-8"),
  ...readdirSync(SYMBOLS_DIR)
    .filter((name) => name.endsWith(".ts"))
    .map((name) => readFileSync(`${SYMBOLS_DIR}/${name}`, "utf-8")),
];

const implementedRaw = new Set(
  symbolSources.flatMap((source) => [...source.matchAll(/(\w+):\s*\{/g)].map((m) => m[1]!)),
);
const implemented = new Set(
  [...implementedRaw].map((s) => s.replace(/W$/, "")),
);

const exampleSources = existsSync(EXAMPLES_DIR)
  ? readdirSync(EXAMPLES_DIR)
      .filter((name) => name.endsWith(".ts") && name !== "index.ts")
      .map((name) => readFileSync(`${EXAMPLES_DIR}/${name}`, "utf-8"))
  : [];

const testSources = existsSync(TESTS_DIR)
  ? readdirSync(TESTS_DIR)
      .filter((name) => name.endsWith(".test.ts"))
      .map((name) => readFileSync(`${TESTS_DIR}/${name}`, "utf-8"))
  : [];

const exampleFuncs = new Set(
  exampleSources.flatMap((src) => [...src.matchAll(/Raylib\.(\w+)\(/g)].map((m) => m[1]!)),
);

const testFuncs = new Set(
  testSources.flatMap((src) => [...src.matchAll(/Raylib\.(\w+)\(/g)].map((m) => m[1]!)),
);

function camelFromC(cname: string): string {
  return cname[0]!.toLowerCase() + cname.slice(1);
}

interface Section {
  title: string;
  functions: string[];
}

const sections: Section[] = [];
let currentSection: Section | null = null;

const lines = h.split("\n");
const funcRe = /^RLAPI\s+\w[\w\s*]+\s+(\w+)\s*\(/;
const separatorRe = /^\/\/-{20,}/;

for (let i = 0; i < lines.length; i++) {
  const trimmed = lines[i]!.trim();

  if (separatorRe.test(trimmed)) {
    if (i + 1 < lines.length) {
      const next = lines[i + 1]!.trim();
      const titleMatch = /^\/\/\s+(.+)$/.exec(next);
      if (titleMatch) {
        const title = titleMatch[1]!.trim();
        if (
          !title.match(/^[-=]/) &&
          !title.startsWith("NOTE") &&
          !title.startsWith("WARNING")
        ) {
          currentSection = { title, functions: [] };
          sections.push(currentSection);
          continue;
        }
      }
    }
  }

  const funcMatch = funcRe.exec(trimmed);
  if (funcMatch && currentSection) {
    currentSection.functions.push(funcMatch[1]!);
  }
}

let md = `# rraylib Progress Tracker\n\n`;
md += `> Auto-generated by \`bun run progress\`\n\n`;

let totalDone = 0;
let totalFuncs = 0;

interface FnInfo {
  name: string;
  hasExample: boolean;
  hasTest: boolean;
}

const results: {
  title: string;
  done: FnInfo[];
  missing: FnInfo[];
}[] = [];

for (const sec of sections) {
  if (sec.functions.length === 0) continue;

  const done: FnInfo[] = [];
  const missing: FnInfo[] = [];

  for (const fn of sec.functions) {
    const camel = camelFromC(fn);
    const info: FnInfo = {
      name: fn,
      hasExample: exampleFuncs.has(camel),
      hasTest: testFuncs.has(camel),
    };
    if (implemented.has(fn)) {
      done.push(info);
    } else {
      missing.push(info);
    }
  }

  totalDone += done.length;
  totalFuncs += sec.functions.length;

  results.push({ title: sec.title, done, missing });
}

const pct = totalFuncs > 0 ? ((totalDone / totalFuncs) * 100).toFixed(1) : "0";

const allFuncs = results.flatMap((r) => [...r.done, ...r.missing]);
const totalWithExample = allFuncs.filter((f) => f.hasExample).length;
const totalWithTest = allFuncs.filter((f) => f.hasTest).length;

md += `## Overall: ${totalDone}/${totalFuncs} (${pct}%)\n\n`;
md += `| Implemented | Examples | Tests |\n`;
md += `|-------------|----------|-------|\n`;
md += `| ${totalDone}/${totalFuncs} | ${totalWithExample}/${totalFuncs} | ${totalWithTest}/${totalFuncs} |\n\n`;

const barLen = 30;
const filled = Math.round((totalDone / totalFuncs) * barLen);
md += `[${"█".repeat(filled)}${"░".repeat(barLen - filled)}]\n\n`;

for (const r of results) {
  const total = r.done.length + r.missing.length;
  const secPct = total > 0 ? ((r.done.length / total) * 100).toFixed(0) : "0";
  const secExample = r.done.filter((f) => f.hasExample).length + r.missing.filter((f) => f.hasExample).length;
  const secTest = r.done.filter((f) => f.hasTest).length + r.missing.filter((f) => f.hasTest).length;
  const icon = r.missing.length === 0 ? "✅" : r.done.length === 0 ? "⬜" : "🔶";
  md += `### ${icon} ${r.title} (${r.done.length}/${total} — ${secPct}% | 📝${secExample} 🧪${secTest})\n\n`;

  if (r.missing.length > 0) {
    md += `<details><summary><b>Missing (${r.missing.length})</b></summary>\n\n`;
    for (const fn of r.missing) {
      const ex = fn.hasExample ? "📝" : "";
      const ts = fn.hasTest ? "🧪" : "";
      md += `- [ ] \`${fn.name}\` ${ex}${ts}\n`;
    }
    md += `\n</details>\n\n`;
  }

  if (r.done.length > 0) {
    md += `<details><summary>Done (${r.done.length})</summary>\n\n`;
    for (const fn of r.done) {
      const ex = fn.hasExample ? "📝" : "";
      const ts = fn.hasTest ? "🧪" : "";
      md += `- [x] \`${fn.name}\` ${ex}${ts}\n`;
    }
    md += `\n</details>\n\n`;
  }
}

writeFileSync(OUTPUT, md);
console.log(`PROGRESS.md generated: ${totalDone}/${totalFuncs} (${pct}%)`);
