import { FFIType } from 'bun:ffi';
const { i32, cstring, bool, f32, f64, ptr } = FFIType;

export const windowDirectSymbols = {
  InitWindow: { args: [i32, i32, cstring], returns: FFIType.void },
  CloseWindow: { args: [], returns: FFIType.void },
  WindowShouldClose: { args: [], returns: bool },
  BeginDrawing: { args: [], returns: FFIType.void },
  EndDrawing: { args: [], returns: FFIType.void },
  SetTargetFPS: { args: [i32], returns: FFIType.void },
  GetFrameTime: { args: [], returns: f32 },
  IsWindowReady: { args: [], returns: bool },
  IsWindowFullscreen: { args: [], returns: bool },
  IsWindowHidden: { args: [], returns: bool },
  IsWindowMinimized: { args: [], returns: bool },
  IsWindowMaximized: { args: [], returns: bool },
  IsWindowFocused: { args: [], returns: bool },
  IsWindowResized: { args: [], returns: bool },
  IsWindowState: { args: [i32], returns: bool },
  SetWindowState: { args: [i32], returns: FFIType.void },
  ClearWindowState: { args: [i32], returns: FFIType.void },
  ToggleFullscreen: { args: [], returns: FFIType.void },
  ToggleBorderlessWindowed: { args: [], returns: FFIType.void },
  MaximizeWindow: { args: [], returns: FFIType.void },
  MinimizeWindow: { args: [], returns: FFIType.void },
  RestoreWindow: { args: [], returns: FFIType.void },
  SetWindowTitle: { args: [cstring], returns: FFIType.void },
  SetWindowPosition: { args: [i32, i32], returns: FFIType.void },
  SetWindowMonitor: { args: [i32], returns: FFIType.void },
  SetWindowMinSize: { args: [i32, i32], returns: FFIType.void },
  SetWindowMaxSize: { args: [i32, i32], returns: FFIType.void },
  SetWindowSize: { args: [i32, i32], returns: FFIType.void },
  SetWindowOpacity: { args: [f32], returns: FFIType.void },
  SetWindowFocused: { args: [], returns: FFIType.void },
  GetScreenWidth: { args: [], returns: i32 },
  GetScreenHeight: { args: [], returns: i32 },
  GetRenderWidth: { args: [], returns: i32 },
  GetRenderHeight: { args: [], returns: i32 },
  GetMonitorCount: { args: [], returns: i32 },
  GetCurrentMonitor: { args: [], returns: i32 },
  GetMonitorWidth: { args: [i32], returns: i32 },
  GetMonitorHeight: { args: [i32], returns: i32 },
  GetMonitorPhysicalWidth: { args: [i32], returns: i32 },
  GetMonitorPhysicalHeight: { args: [i32], returns: i32 },
  GetMonitorRefreshRate: { args: [i32], returns: i32 },
  GetMonitorName: { args: [i32], returns: ptr },
  SetClipboardText: { args: [cstring], returns: FFIType.void },
  GetClipboardText: { args: [], returns: ptr },
  EnableEventWaiting: { args: [], returns: FFIType.void },
  DisableEventWaiting: { args: [], returns: FFIType.void },
  ShowCursor: { args: [], returns: FFIType.void },
  HideCursor: { args: [], returns: FFIType.void },
  IsCursorHidden: { args: [], returns: bool },
  EnableCursor: { args: [], returns: FFIType.void },
  DisableCursor: { args: [], returns: FFIType.void },
  IsCursorOnScreen: { args: [], returns: bool },
  EndTextureMode: { args: [], returns: FFIType.void },
  BeginBlendMode: { args: [i32], returns: FFIType.void },
  EndBlendMode: { args: [], returns: FFIType.void },
  BeginScissorMode: { args: [i32, i32, i32, i32], returns: FFIType.void },
  EndScissorMode: { args: [], returns: FFIType.void },
  GetTime: { args: [], returns: f64 },
  GetFPS: { args: [], returns: i32 },
  SwapScreenBuffer: { args: [], returns: FFIType.void },
  PollInputEvents: { args: [], returns: FFIType.void },
  WaitTime: { args: [f64], returns: FFIType.void },
  SetRandomSeed: { args: [i32], returns: FFIType.void },
  GetRandomValue: { args: [i32, i32], returns: i32 },
  TakeScreenshot: { args: [cstring], returns: FFIType.void },
  SetConfigFlags: { args: [i32], returns: FFIType.void },
  OpenURL: { args: [cstring], returns: FFIType.void },
  SetTraceLogLevel: { args: [i32], returns: FFIType.void },
} as const;

export const windowWrapperSymbols = {
  ClearBackgroundW: { args: [i32], returns: FFIType.void },
  GetMonitorPositionW: { args: [ptr, i32], returns: FFIType.void },
  GetWindowPositionW: { args: [ptr], returns: FFIType.void },
  GetWindowScaleDPIW: { args: [ptr], returns: FFIType.void },
  BeginTextureModeW: { args: [i32, i32, i32], returns: FFIType.void },
  TraceLogW: { args: [i32, cstring], returns: FFIType.void },
  SetWindowIconW: { args: [i32], returns: FFIType.void },
  GetClipboardImageW: { args: [], returns: i32 },
  SetWindowIconsW: { args: [ptr, i32], returns: FFIType.void },
} as const;
